### ISSUE TITLE
better readiness probe for kafka

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-deploy-kube#355]
We need a good external check for Kafka being ready that can be used in the `openwhisk.readiness.waitForKafka` macro in _readiness.tpl.

The current macro checks for zookeeper being up, then sleeps for 10 seconds (assuming this is enough time for kafka to be ready).  Ideally, we could make a connection to the kafka service and verify that it is actually ready.  This would (a) be accurate and (b) usually cut about 5 seconds of latency out of Chart deployment since the 10 second sleep is fairly conservative.

**Comment by larandersson** [comment]
@dgrove-oss There should probably also be Kubernetes readinessProbe and livenessProbe (#428).

**Comment by dgrove-oss** [comment]
Fixed in #672
