### ISSUE TITLE
Enable metrics and metric configuration

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-deploy-kube#396]
Add Helm chart support for enabling and configuring Kamon metrics from controller and invoker.

**Comment by sigmaadam** [comment]
where can I get this helm chat?

**Comment by dgrove-oss** [comment]
@daisy-ycguo - there have been a couple of slack threads related to enabling metrics for openwhisk deployed on kube.  For example https://openwhisk-team.slack.com/archives/C3TPCAQG1/p1547131919206800 and https://openwhisk-team.slack.com/archives/C3TPCAQG1/p1548146225427900.

The goal is to learn from these threads and enhance our Helm chart to make it simple to enable metrics when deploying openwhisk onto kube.

**Comment by dgrove-oss** [comment]
It might also make sense to assume https://github.com/apache/incubator-openwhisk/pull/4227 gets merged upstream and then enable Prometheus integration that way.

**Comment by CPattanayak** [comment]
@dgrove-oss -we notice this change is there in master please let us know how we can use this in helm chart 
added below change in my yml
whisk:
  metrics:
    prometheus-enabled: true
it is not working for me

**Comment by dgrove-oss** [comment]
@CPattanayak -- sorry, I have not had a chance to try this myself.  We did refresh the Helm chart to a newer set of commits yesterday in #450.  Perhaps that might help if you try again.

**Comment by dgrove-oss** [comment]
I believe this is covered by the metrics PR #520 which has been merged
