### ISSUE TITLE
Unready pods after deployed on cloud

### ISSUE THREAD

**Issue by wilsonYongchen** [apache/openwhisk-deploy-kube#481]

**Comment by wilsonYongchen** [comment]
I have looked through the tutorial for deployment and install k8s and helm on the cloud. After I finish all the steps and try to create an action, an error appears as follows:
        error: Unable to create action 'helloPython': Put https://192.168.33.13:31001/api/v1/namespaces/_/actions/helloPython?overwrite=false: dial tcp 192.168.33.13:31001: i/o timeout
Run 'wsk --help' for usage.

the Following is the helm status owdev result:
root@node-0:~/incubator-openwhisk-deploy-kube# helm status owdev
LAST DEPLOYED: Sun Jun 16 15:10:16 2019
NAMESPACE: openwhisk
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                         DATA  AGE
owdev-db.config              10    66s
owdev-init-couchdb           1     66s
owdev-install-packages-cm    1     66s
owdev-invoker-scripts        2     66s
owdev-nginx                  1     66s
owdev-tests-package-checker  1     66s
owdev-tests-smoketest        1     66s
owdev-whisk.config           9     66s
owdev-zookeeper              1     66s

==> v1/Deployment
NAME                    READY  UP-TO-DATE  AVAILABLE  AGE
owdev-alarmprovider     0/1    1           0          65s
owdev-apigateway        1/1    1           1          65s
owdev-cloudantprovider  0/1    1           0          65s
owdev-couchdb           0/1    1           0          65s
owdev-kafkaprovider     0/1    1           0          65s
owdev-nginx             0/1    1           0          65s
owdev-redis             0/1    1           0          65s

==> v1/Job
NAME                    COMPLETIONS  DURATION  AGE
owdev-init-couchdb      0/1          64s       64s
owdev-install-packages  0/1          64s       64s

==> v1/Pod
NAME            READY  STATUS   RESTARTS  AGE
owdev-wskadmin  1/1    Running  0         65s

==> v1/Pod(related)
NAME                                    READY  STATUS             RESTARTS  AGE
owdev-alarmprovider-754b8f648f-qllgg    0/1    Init:0/1           0         65s
owdev-apigateway-7644cd4ff-j99ng        1/1    Running            0         65s
owdev-cloudantprovider-b9d69f59d-l4wwp  0/1    Init:0/1           0         65s
owdev-controller-0                      0/1    Init:0/2           0         65s
owdev-couchdb-58d759dcb9-f6wpk          0/1    ContainerCreating  0         65s
owdev-init-couchdb-2hx8n                0/1    ContainerCreating  0         64s
owdev-install-packages-kg79b            0/1    Init:0/1           0         64s
owdev-invoker-0                         0/1    Init:0/1           0         64s
owdev-kafka-0                           0/1    Init:0/1           0         64s
owdev-kafkaprovider-55db8d975-m9s86     0/1    Init:0/1           0         65s
owdev-nginx-86d777cd8f-zht78            0/1    ContainerCreating  0         65s
owdev-redis-6d5466ff6c-fm44r            0/1    ContainerCreating  0         65s
owdev-zookeeper-0                       0/1    ContainerCreating  0         63s

==> v1/Role
NAME           AGE
owdev-invoker  66s

==> v1/RoleBinding
NAME              AGE
owdev-allow-view  66s
owdev-invoker     66s

==> v1/Secret
NAME                        TYPE    DATA  AGE
owdev-db.auth               Opaque  2     66s
owdev-docker.registry.auth  Opaque  2     66s
owdev-nginx                 tls     2     66s
owdev-whisk.auth            Opaque  2     66s

==> v1/Service
NAME              TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)                     AGE
owdev-apigateway  ClusterIP  10.98.250.246  <none>       8080/TCP,9000/TCP           66s
owdev-controller  ClusterIP  10.98.181.59   <none>       8080/TCP                    65s
owdev-couchdb     ClusterIP  10.109.12.4    <none>       5984/TCP                    65s
owdev-kafka       ClusterIP  None           <none>       9092/TCP                    65s
owdev-nginx       NodePort   10.99.93.6     <none>       80:30382/TCP,443:31001/TCP  65s
owdev-redis       ClusterIP  10.111.94.23   <none>       6379/TCP                    65s
owdev-zookeeper   ClusterIP  None           <none>       2181/TCP,2888/TCP,3888/TCP  65s

==> v1/ServiceAccount
NAME           SECRETS  AGE
owdev-core     1        66s
owdev-invoker  1        66s

==> v1/StatefulSet
NAME              READY  AGE
owdev-controller  0/1    65s
owdev-invoker     0/1    65s
owdev-kafka       0/1    65s
owdev-zookeeper   0/1    65s

Did I miss any installation or some files I still need to create and work on?

**Comment by wilsonYongchen** [comment]
Following is kubectl -n openwhisk get pods  result:
NAME                                     READY   STATUS      RESTARTS   AGE
owdev-alarmprovider-754b8f648f-bgdsv     0/1     Pending     0          17s
owdev-alarmprovider-754b8f648f-qllgg     0/1     Evicted     0          6m40s
owdev-apigateway-7644cd4ff-bc8pw         0/1     Pending     0          104s
owdev-apigateway-7644cd4ff-j99ng         0/1     Evicted     0          6m40s
owdev-cloudantprovider-b9d69f59d-l4wwp   0/1     Evicted     0          6m40s
owdev-cloudantprovider-b9d69f59d-mf5g7   0/1     Pending     0          21s
owdev-controller-0                       0/1     Pending     0          88s
owdev-couchdb-58d759dcb9-f6wpk           0/1     Evicted     0          6m40s
owdev-couchdb-58d759dcb9-m72v8           0/1     Pending     0          103s
owdev-init-couchdb-2hx8n                 0/1     Completed   0          6m39s
owdev-install-packages-kg79b             0/1     Evicted     0          6m39s
owdev-install-packages-knmlg             0/1     Pending     0          25s
owdev-invoker-0                          0/1     Pending     0          87s
owdev-kafka-0                            0/1     Pending     0          2m37s
owdev-kafkaprovider-55db8d975-m9s86      1/1     Running     0          6m40s
owdev-nginx-86d777cd8f-z9twz             0/1     Pending     0          103s
owdev-nginx-86d777cd8f-zht78             0/1     Evicted     0          6m40s
owdev-redis-6d5466ff6c-fm44r             0/1     Evicted     0          6m40s
owdev-redis-6d5466ff6c-vsr4x             0/1     Pending     0          12s
owdev-wskadmin                           0/1     Evicted     0          6m40s
owdev-zookeeper-0                        0/1     Pending     0          57s

**Comment by neerajmangal** [comment]
It could happen if node running your pods is low on resources. 
Can you run below to check the reason of the pod eviction?  

`kubectl get pod -o go-template='{{.status.message}}' podname`

**Comment by dgrove-oss** [comment]
> owdev-zookeeper-0 0/1 Pending 0 57s

Take a look at zookeeper to see why it isn't coming up.  You may need to intervene to be sure you have the latest zookeeper image from dockerhub to work around #469.

**Comment by dgrove-oss** [comment]
Closing as stale
