### ISSUE TITLE
Project 'tests' not found

### ISSUE THREAD

**Issue by SamChb72** [apache/openwhisk-deploy-kube#496]
Hello,
I want to test the install with command

`./gradlew :tests:testSystemBasic -Dwhisk.auth=$WHISK_AUTH -Dwhisk.server=https://$WHISK_SERVER -Dopenwhisk.home=`pwd` --info
`

as mentioned in Readme
but the tests directors seems missing????
I have output:

`
> Configure project : 
Evaluating root project incubator-openwhisk-deploy-kube using build file /home/xxx/incubator-openwhisk-deploy-kube/build.gradle
All projects evaluated.
FAILURE: Build failed with an exception.
What went wrong:
Project 'tests' not found in root project 'incubator-openwhisk-deploy-kube'.
`

**Comment by dgrove-oss** [comment]
the tests directory is located in the main openwhisk project. (https://github.com/apache/incubator-openwhisk).  The assumption is that you would have that project checked out as well and execute the test command there.  Looks like the documentation could be improved.

As a quick smoke test, you could also try `helm test` which will run a few simple tests from a pod inside of the cluster.
