### ISSUE TITLE
Not able to get OpenWhisk up on minikube on ubuntu 18.04

### ISSUE THREAD

**Issue by urmilb** [apache/openwhisk-deploy-kube#521]
Hi,

From last three days, I am trying to get the Openwhisk up on a 8 gb ram laptop running ubuntu 18.04 using the steps given at https://github.com/apache/openwhisk-deploy-kube

Started with a fresh ubuntu setup, steps followed:
1. installed the virtualbox
2. installed the virtualbox-ext-pack
3. installed asdf: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4
4. echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc 
5. echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
6. sudo apt install   automake autoconf libreadline-dev   libncurses-dev libssl-dev libyaml-dev   libxslt-dev libffi-dev libtool unixodbc-dev   unzip curl
7. asdf plugin-add kubectl
8. asdf plugin-add minikube
9. asdf install kubectl 1.10.5 (also tried 1.9.0 in second attempt as was suggested at https://medium.com/openwhisk/deploying-openwhisk-on-kubernetes-3f55f781fbab)
10. asdf global kubectl 1.10.5 (also 1.9.0 in second attempt)
11. asdf install minikube 0.28.2 (also 0.25.2 in second attempt)
12. asdf global minikube 0.28.2  (also 0.25.2 in second attempt)
13.  minikube config set kubernetes-version v1.10.5
minikube config set cpus 2
minikube config set memory 4096
minikube config set WantUpdateNotification false
14. minikube start --cpus 2 --memory 4096 --kubernetes-version=v1.10.5     (for version 0.25.2 used --extra-config=apiserver.Authorization.Mode=RBAC )
15. minikube ssh -- sudo ip link set docker0 promisc on
16. git clone https://github.com/apache/openwhisk-deploy-kube.git
17. Created > gedit mycluster.yaml
whisk:
  ingress:
    type: NodePort
    apiHostName: 192.168.99.100
    apiHostPort: 31001

nginx:
  httpsNodePort: 31001

18. curl -LO https://git.io/get_helm.sh
chmod 700 get_helm.sh
 ./get_helm.sh
helm init
19. kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
20. kubectl label nodes --all openwhisk-role=invoker
21. helm install ./openwhisk-deploy-kube/helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml

Now even after multiple tries all the pods are not starting, 

> kubectl get pods -n openwhisk
gives:

NAME                                      READY     STATUS     RESTARTS   AGE
owdev-apigateway-66644495b8-sbjqk         1/1       Running    0          1d
owdev-cloudantprovider-5b4f98744d-zzsxd   0/1       Init:0/1   0          1d
owdev-controller-0                        0/1       Running    16         1d
owdev-couchdb-86c57b8b8b-845hl            1/1       Running    0          1d
owdev-install-packages-jjsc6              0/1       Init:0/1   0          1d
owdev-invoker-pp699                       0/1       Init:1/2   0          1d
owdev-kafka-0                             1/1       Running    0          1d
owdev-kafkaprovider-56c9c98899-jz9wp      0/1       Init:0/1   0          1d
owdev-nginx-844c55df74-fgr98              1/1       Running    0          1d
owdev-redis-77c6b97946-hqzvn              1/1       Running    0          1d
owdev-wskadmin                            1/1       Running    0          1d
owdev-zookeeper-0                         1/1       Running    0          1d

pls refer output of describe pods in attached, please suggest:
[error.txt](https://github.com/apache/openwhisk-deploy-kube/files/3567607/error.txt)

**Comment by chetanmeh** [comment]
From the details provided controller is not up
```
Name:           owdev-controller-0
Namespace:      openwhisk
Node:           minikube/192.168.99.100
...
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
  Warning  Unhealthy              37m (x5 over 37m)   kubelet, minikube  Readiness probe failed: Get http://172.17.0.12:8080/ping: dial tcp 172.17.0.12:8080: getsockopt: connection refused
  Normal   Killing                37m (x2 over 37m)   kubelet, minikube  Killing container with id docker://controller:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy              30m (x17 over 37m)  kubelet, minikube  Liveness probe failed: Get http://172.17.0.12:8080/ping: dial tcp 172.17.0.12:8080: getsockopt: connection refused
  Normal   Pulled                 24m (x8 over 37m)   kubelet, minikube  Container image "openwhisk/controller:9bef49f" already present on machine
  Warning  BackOff                5m (x132 over 36m)  kubelet, minikube  Back-off restarting failed container
```

Can you check and share logs for controller
```
kubectl logs owdev-controller-0
```

That may provide some clue on whats wrong here

**Comment by urmilb** [comment]
Thanks Chetanmeh. I am getting below output while executing : kubectl logs owdev-controller-0
Error from server (NotFound): pods "owdev-controller-0" not found


Current status of pods after restart :
kubectl get pods -n openwhisk
NAME                                      READY     STATUS             RESTARTS   AGE
owdev-apigateway-66644495b8-bm585         1/1       Running            0          7m
owdev-cloudantprovider-5b4f98744d-96hs9   0/1       Init:0/1           0          7m
owdev-controller-0                        0/1       CrashLoopBackOff   5          7m
owdev-couchdb-86c57b8b8b-cxdnt            1/1       Running            0          7m
owdev-install-packages-pwhp5              0/1       Init:0/1           0          7m
owdev-invoker-kmt7b                       0/1       Init:1/2           0          7m
owdev-kafka-0                             1/1       Running            0          7m
owdev-kafkaprovider-56c9c98899-bppxk      0/1       Init:0/1           0          7m
owdev-nginx-844c55df74-f7bf4              1/1       Running            0          7m
owdev-redis-77c6b97946-5zkr2              1/1       Running            0          7m
owdev-wskadmin                            1/1       Running            0          7m
owdev-zookeeper-0                         1/1       Running            0          7m

Sharing output of following commands if it helps:
>helm status owdev > helm_status.txt
>helm get owdev > helm_get.txt
>kubectl describe pods -n openwhisk > describe_pods.txt
[helm_get.txt](https://github.com/apache/openwhisk-deploy-kube/files/3569641/helm_get.txt)
[describe_pods.txt](https://github.com/apache/openwhisk-deploy-kube/files/3569646/describe_pods.txt)
[helm_status.txt](https://github.com/apache/openwhisk-deploy-kube/files/3569647/helm_status.txt)

**Comment by urmilb** [comment]
I tried below command, please refer the output below:
kubectl logs owdev-controller-0 -n openwhisk

Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
[2019-09-03T13:29:34.623Z] [INFO] Slf4jLogger started
[2019-09-03T13:29:36.427Z] [INFO] Started the Kamon StatsD reporter
[2019-09-03T13:29:36.456Z] [INFO] Loaded metric reporter [kamon.statsd.StatsDReporter]
[2019-09-03T13:29:37.817Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.triggers.fires.perMinute
[2019-09-03T13:29:37.831Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.sequence.maxLength
[2019-09-03T13:29:37.834Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.concurrent
[2019-09-03T13:29:37.838Z] [INFO] [#tid_sid_unknown] [Config] environment set value for limits.actions.invokes.perMinute
[2019-09-03T13:29:37.840Z] [INFO] [#tid_sid_unknown] [Config] environment set value for runtimes.manifest
[2019-09-03T13:29:37.843Z] [INFO] [#tid_sid_unknown] [Config] environment set value for kafka.hosts
[2019-09-03T13:29:37.846Z] [INFO] [#tid_sid_unknown] [Config] environment set value for port
[2019-09-03T13:29:40.612Z] [INFO] [#tid_sid_unknown] [KafkaMessagingProvider] topic completed0 already existed
[2019-09-03T13:29:41.446Z] [INFO] [#tid_sid_unknown] [KafkaMessagingProvider] topic health already existed
[2019-09-03T13:29:42.179Z] [INFO] [#tid_sid_unknown] [KafkaMessagingProvider] topic cacheInvalidation already existed
[2019-09-03T13:29:42.772Z] [INFO] [#tid_sid_unknown] [KafkaMessagingProvider] topic events already existed
[2019-09-03T13:29:43.937Z] [INFO] [#tid_sid_controller] [Controller] starting controller instance 0 [marker:controller_startup0_counter:6131]
[2019-09-03T13:29:44.659Z] [INFO] [#tid_sid_unknown] [Controller] Shutting down Kamon with coordinated shutdown

**Comment by neerajmangal** [comment]
Hi @urmilb, 

Please check https://github.com/apache/openwhisk-deploy-kube/blob/a4a008cced82627ca8c5229e6568f2ccdfaf92f5/docs/troubleshooting.md#controller-and-invoker-cannot-connect-to-kafka , if `minikube ssh -- sudo ip link set docker0 promisc on` does not work, check `kubectl describe pod owdev-controller-0`, it might be possible that the controller is being killed/restarted by kubelet due to liveness probe failure if it does not come within that time.

if that is the case you can increase the livenessProb's `initialDelayinSeconds` setting. Please refer to https://github.com/apache/openwhisk-deploy-kube/issues/477 and https://github.com/apache/openwhisk-deploy-kube/issues/478.

**Comment by urmilb** [comment]
Thanks @neerajmangal , I would try the same and update.

JFYI, i see the controller status "running" in between , but the owdev-install-packages and owdev-invoker never comes up. 

please suggest if my system configuration and software versions are fine to get openwhisk up:
laptop with 8 GB ram
Ubuntu 18.04
kubectl 1.10.5
minukube 0.28.2

It would help if some one can direct me to a tutorial which they have tried recently and it worked for them.

**Comment by neerajmangal** [comment]
Hi @urmilb, 

I guess, controller status `running` between is because of its started per readiness probe but not fully initialized for `livenessProbe` to succeed. This causes kubelet to think that it's not up and restarted. Invoker pod depends on the controller so it will not come up till the controller comes up fully. 

owdev-install-packages is a job so it will show status as complete if successful otherwise you need to check what's wrong with it. 

I haven't tried on the similar setup you mentioned so can't comment on this, but you should check quota limits on your namespace. Also, there are default limits applied by Kubernetes if not specified on pod basis so check them as well based on the number of pods you are configuring.

**Comment by urmilb** [comment]
Thanks @neerajmangal , i updated mycluster.yaml as below and now I have all pods up barring the 

whisk:
  runtimes: "runtimes-minimal-travis.json"
  ingress:
    type: NodePort
    apiHostName: 192.168.99.100
    apiHostPort: 31001

nginx:
  httpsNodePort: 31001

k8s:
  persistence:
    enabled: false

providers:
  alarm:
    enabled: false

invoker:
  containerFactory:
    impl: "kubernetes"

probes:
  controller:
    livenessProbe:
      initialDelaySeconds: 200
      periodSeconds: 200
      timeoutSeconds: 600

pdb:
  enable: true
  zookeeper:
    maxUnavailable: 1
  controller:
    maxUnavailable: 1
  invoker:
    maxUnavailable: 1

NAME                                                         READY     STATUS      RESTARTS   AGE
owdev-apigateway-66644495b8-sbb54                            1/1       Running     0          12m
owdev-cloudantprovider-5b4f98744d-52vzn                      1/1       Running     0          12m
owdev-controller-0                                           1/1       Running     0          12m
owdev-couchdb-86c57b8b8b-r7gm6                               1/1       Running     0          12m
owdev-init-couchdb-sc99l                                     0/1       Completed   0          12m
owdev-install-packages-pw6zr                                 1/1       Running     0          12m
owdev-invoker-0                                              1/1       Running     0          12m
owdev-kafka-0                                                1/1       Running     0          12m
owdev-kafkaprovider-56c9c98899-dmvrl                         1/1       Running     0          12m
owdev-nginx-844c55df74-6j6q7                                 1/1       Running     0          12m
owdev-redis-77c6b97946-prr8r                                 1/1       Running     0          12m
owdev-wskadmin                                               1/1       Running     0          12m
owdev-zookeeper-0                                            1/1       Running     0          12m
wskowdev-invoker-00-2-whisksystem-invokerhealthtestaction0   0/1       Pending     0          22s
