### ISSUE TITLE
kubernetes-sigs/kubeadm-dind-cluster has been replaced by kind

### ISSUE THREAD

**Issue by gabrielschulhof** [apache/openwhisk-deploy-kube#523]
The instructions at

https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-dind-cluster.md#creating-the-kubernetes-cluster

include

```bash
$ wget https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.10.sh
```

This is currently 404, and https://github.com/kubernetes-sigs/kubeadm-dind-cluster is an archived repository. It links to its replacement, https://kind.sigs.k8s.io/

Basically, it seems one of the prerequisites for openwhisk has changed. I'm not sure if `kind` accepts `USE_HAIRPIN=true`, however, I will certainly run `kind create cluster` with `USE_HAIRPIN=true`.

**Comment by dgrove-oss** [comment]
Thanks. I had updated our TravisCI setup with the archived URLs, but I forgot about the user-facing documentation.  Submitted #524 to fix that oversight.

If you get `kind` working, would be awesome to get a doc PR describing the steps.  Issue #508 is also about dind deprecation.

**Comment by dgrove-oss** [comment]
Updated docs to note deprecation.  Actually switching to kind will be tracked by #508
