### ISSUE TITLE
Invoker is failing to start

### ISSUE THREAD

**Issue by murthychandrappa** [apache/openwhisk-deploy-kube#539]
Hi,

I am using helm chart to deploy openwhisk on our on-prem kubernetes cluster. All pods are up and running except invoker and its failing with below error message.

![image](https://user-images.githubusercontent.com/25990601/67241598-b63c1600-f421-11e9-8664-03a5a1935473.png)

```
C:\Projects\FaaS\trial1>kubectl logs owdev-invoker-c2rdp -n openwhisk
Error from server (BadRequest): container "invoker" in pod "owdev-invoker-c2rdp" is waiting to start: PodInitializing
```
kubectl describe pod for one of the invoker give me below events.
![image](https://user-images.githubusercontent.com/25990601/67241818-2d71aa00-f422-11e9-8819-974cbcb532ae.png)

Could you please let me know how do i debug and run openwhisk?

**Comment by dgrove-oss** [comment]
My guess is that your on-prem kuberetes cluster is using `containerd` instead of `docker` as the container runtime.   This is incompatible with using the DockerContainerFactory.  Try adding the configuration to your mycluster.yaml to use the KubernetesContainerFactory (https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/configurationChoices.md#invoker-container-factory) and redeploying.

**Comment by murthychandrappa** [comment]
That's perfect. After changing the configuration to use Kubernetes, invoker pods are coming up.
But _install-packages_ pod is failing with below error message. My cluster has 3 nodes and I have labelled all 3 nodes as invoker.
```
Setting git proxy in myTask.sh
Cloning into 'openwhisk'...
/openwhisk /
Note: checking out 'b05b7ff21c414aac31a325c68ae522e5c8a17dd6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b05b7ff2 Update k8s client to 4.4.0 from 4.0.3 (#4606)
/
/openwhisk/ansible/roles/routemgmt/files /
Installing apimgmt package
error: Package update failed: Put https://:31001/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp :31001: getsockopt: connection refused
Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': Get https://:31001/api/v1/namespaces/whisk.system/actions/routemgmt/getApi?code=false: dial tcp :31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/createApi': Get https://:31001/api/v1/namespaces/whisk.system/actions/routemgmt/createApi?code=false: dial tcp :31001: getsockopt: connection refused
Run 'wsk --help' for usage.
error: Unable to get action 'routemgmt/deleteApi': Get https://:31001/api/v1/namespaces/whisk.system/actions/routemgmt/deleteApi?code=false: dial tcp :31001: getsockopt: connection refused
Run 'wsk --help' for usage.
```

**Comment by dgrove-oss** [comment]
The problem is `https://:31001/api/v1/namespaces/whisk.system/actions/`.  It's missing the hostname.   That suggests you didn't set `whisk.ingress.apiHostName` in your `mycluster.yaml`

**Comment by murthychandrappa** [comment]
Thank you for your quick reply. WE use NSX-T load balancer so after adding below property in ```mycluster.yaml```, i was able to successfully deploy
```whisk.ingress.type: LoadBalancer```

Also, as I am trying to install openwhisk on on-prem cluster which is behind firewall and do not have direct access to internet to download artifacts, i need to add proxy for git and NPM as in ```helm\openwhisk\configMapFiles\installPackages\myTask.sh``` file.
```git config --global http.proxy http://<proxy_user_name>:<proxy_password>@<proxy_host>:<proxy_port>```
```npm config set proxy http://<proxy_user_name>:<proxy_password>@<proxy_host>:<proxy_port>```
