### ISSUE TITLE
How to separate workloads in openwhisk?

### ISSUE THREAD

**Issue by murthychandrappa** [apache/openwhisk-deploy-kube#541]
Hi,

I am able to setup openwhisk on on-prem kubernetes cluster and I would like to offer to some of pilot customers in our organization. Before offering, I would like to create a isolation or logical separation of workloads like in kubernetes we create namespace and can give access to customers to specific namespaces. Basically each customer should have access to only their workloads and should not be able to manage other customer work loads.

I still have day2 operation questions and is there anyone I can setup a call to understand bit more on the openwhisk platform? We have thousands of developers and hundreds of team so would like to make sure openwhisk can support production workloads with high availability.

**Comment by rabbah** [comment]
hi @murthychandrappa feel free to reach out to me on slack or email me.

**Comment by murthychandrappa** [comment]
Thank you @rabbah for quick response. I just sent an email as I had some problem joining slack.
