### ISSUE TITLE
Unknown Error From API: certificate has expired

### ISSUE THREAD

**Issue by Avik1993** [apache/openwhisk-deploy-kube#548]
wsk property get fails with error:
`x509: certificate has expired or is not yet valid`

How should the SSL certificates be configured in OpenWhisk?

**Comment by dgrove-oss** [comment]
Time to actually fix #305...  certificates have expired again.

**Comment by dgrove-oss** [comment]
Will be fixed by #550.  Closing as duplicate of #305.
