### ISSUE TITLE
Improving scale-up documentation for OpenWhisk deployment on Kubernetes 

### ISSUE THREAD

**Issue by ali-raza-tariq** [apache/openwhisk-deploy-kube#551]
The existing documentation of `OpenWhisk deployment on Kubernetes` does not include much details for scaling-up the deployments from default values. It makes sense to have a separate section on how to scale-up the deployment (e.g. increase concurrency limit) and talk about related errors one might face, in this regard. 

I am thinking about adding a separate section `Scale-up your deployment` on the main page, and adding a separate page in `openwhisk-deploy-kube/docs/` for scale-up related errors. Let me know your thoughts!

**Comment by dgrove-oss** [comment]
Sounds great; thanks for being willing to help improve our documentation!
