### ISSUE TITLE
Install Packages Fails with External CouchDB cluster

### ISSUE THREAD

**Issue by belfhi** [apache/openwhisk-deploy-kube#553]
Hello,
I am trying to deploy Openwhisk on K8s with the helm chart 
but with a CouchDB 3 Node Cluster that was also installed in the 
k8s cluster.
The init-couchdb container completes successfully but the install-packages
container fails:

Installing apimgmt actions
error: Unable to create action 'apimgmt/getApi': Concurrent modification to resource detected.

Failed to deploy routemgmt package; will pause, uninstall, and try again
Deleting routemgmt actions
error: Unable to get action 'routemgmt/getApi': The requested resource does not exist. (code 2b84e3e8b0dcc63b57ff42cd167c0b86)

Any ideas what is going on?

[install-packages.log](https://github.com/apache/openwhisk-deploy-kube/files/3927051/install-packages.log)

**Comment by belfhi** [comment]
[install-packages.log](https://github.com/apache/openwhisk-deploy-kube/files/3926513/install-packages.log)

**Comment by dgrove-oss** [comment]
I'm not a couch-db expert, but https://github.com/apache/openwhisk-deploy-kube/blob/master/helm/openwhisk/configMapFiles/initCouchDB/initdb.sh#L56-#L58 puts the cluster into "single node" mode.  Suspect this could interact badly with a 3 node couchdb cluster.

**Comment by belfhi** [comment]
Hm, yes that could be true... could I do my own initialization of the db? And circumvenrt this issue? Deploying my own CouchDB allows me to configure ingress and tls and make it available to other apps, too. It would be a shame if this didn't work or if I had to use a single node instance.

**Comment by dgrove-oss** [comment]
You could try just cutting out those three lines in the script.  If I'm remembering correctly I did that single node "hack" mainly as a cleaner way to initialize some system databases.  If they are already present in your multi-node instance then it will probably just work.  For the record, this was the commit: https://github.com/apache/openwhisk-deploy-kube/commit/d69eacc26d14e41975dba0a5d22807988f0af1c8

**Comment by belfhi** [comment]
So I found the error, the annotation
nginx.ingress.kubernetes.io/proxy-body-size:  50m
was missing in my CouchDB Nginx Ingress Controller, 
so not an issue with Openwhisk.
