### ISSUE TITLE
Convert to Helm3 to leverage new features

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk-deploy-kube#569]
In particular, we can get some useful validation of values.yaml by using the new json schema support.  I'm prototyping this on a branch (https://github.com/dgrove-oss/openwhisk-deploy-kube/tree/helm3).

**Comment by chetanmeh** [comment]
This would be useful specially getting rid of Tiller which was causing issue on some setups we had having RBAC enabled.

@dgrove-oss Can you create a draft pr based on your current branch. Would be helpful to understand the changes needed as you progress

**Comment by dgrove-oss** [comment]
Sure.   Will do that relatively soon.

BTW, we merged #567 yesterday which actually switched the travisci setup to used helm 3.0.1 for our testing.  Helm v3 can deploy a Helm v2 chart.  So you could start using Helm3 today to avoid requiring tiller.

**Comment by dgrove-oss** [comment]
Migration to Helm 3 was completed a while ago; forgot to close the issue.
