### ISSUE TITLE
I camnot find openwhisk-wskadmin pod

### ISSUE THREAD

**Issue by beth2016** [apache/openwhisk-deploy-kube#570]
I installed openwhisk via helm chart,  And I am pretty sure at one point I saw an openwhisk-wskadmin pod running.   But i dont see it now,   Is there an way way to recreate this pod?

**Comment by dgrove-oss** [comment]
@sciabarracom

**Comment by sciabarra** [comment]
let me check rebuilding the cluster with the current version of the chart

**Comment by beth2016** [comment]
I was able to recreate the pod, so i'm good.  thanks.
