### ISSUE TITLE
Using LoadBalancer instead of Node Port

### ISSUE THREAD

**Issue by beraybentesen** [apache/openwhisk-deploy-kube#578]
I am not sure if this is already provided but I see that Node Port is used in default configuration. Could not find a guide for using Load Balancer to be able to expose the api service. 

Thanks,

**Comment by dgrove-oss** [comment]
Setting up the ingress is different depending on where you provisioned your Kubernetes cluster.  The details for each option (GKE, AKS, EKS, IKS, roll-your-own) are found in the option-specific  doc files in https://github.com/apache/openwhisk-deploy-kube/tree/master/docs
