### ISSUE TITLE
Error: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by beraybentesen** [apache/openwhisk-deploy-kube#579]
I am trying to use Rest Api (cli works with -i parameter btw). How can I fix this issue ? Thanks.

**Comment by dgrove-oss** [comment]
Not sure I understand the question.  If you are using the self-signed certificates then you'll also need to disable SSL certificate checking when using the REST APIs via curl/wget or some other client.

**Comment by dgrove-oss** [comment]
closing as old / not actionable.
