### ISSUE TITLE
couchdb permissions error

### ISSUE THREAD

**Issue by HelenCousins** [apache/openwhisk-deploy-kube#595]
This chart is failing for me, I have many errors but I think the relevent one is in the couchdb pod

[error] 2020-03-30T11:39:15.840326Z couchdb@couchdb0 <0.262.0> -------- Could not open file ./data/_users.couch: permission denied

The pvc exists, and is mounted on the pod, but apparently with bad permissions, but I don't know enough to know how to change the permissions.

The pvc is using hostpathprovisioner, the pvc directory is 777 on the host.

**Comment by ratripathi** [comment]
Could you please share the the details for the CouchDB pod. The output for:
`kubectl describe pod <couchdb pod>`

**Comment by HelenCousins** [comment]
kubectl describe -n openwhisk pod openwhisk-couchdb-645bfbcb7d-8qd82 
Name:         openwhisk-couchdb-645bfbcb7d-8qd82
Namespace:    openwhisk
Priority:     0
Node:         hc7test2-0/192.168.252.30
Start Time:   Mon, 30 Mar 2020 13:26:03 +0000
Labels:       app=openwhisk-openwhisk
              chart=openwhisk-0.2.1
              heritage=Tiller
              name=openwhisk-couchdb
              pod-template-hash=645bfbcb7d
              release=openwhisk
Annotations:  cni.projectcalico.org/podIP: 10.42.1.92/32
              cni.projectcalico.org/podIPs: 10.42.1.92/32
Status:       Running
IP:           10.42.1.92
IPs:
  IP:           10.42.1.92
Controlled By:  ReplicaSet/openwhisk-couchdb-645bfbcb7d
Containers:
  couchdb:
    Container ID:   docker://a4b2891e8d74a29401ec5e2215c4bc335d98559ddb92a681578443d7155e0f31
    Image:          apache/couchdb:2.3
    Image ID:       docker-pullable://apache/couchdb@sha256:9f895c8ae371cb895541e53100e039ac6ae5d30f6f0b199e8470d81d523537ad
    Port:           5984/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 30 Mar 2020 13:58:00 +0000
      Finished:     Mon, 30 Mar 2020 13:58:03 +0000
    Ready:          False
    Restart Count:  11
    Environment:
      COUCHDB_USER:      <set to the key 'db_username' in secret 'openwhisk-db.auth'>  Optional: false
      COUCHDB_PASSWORD:  <set to the key 'db_password' in secret 'openwhisk-db.auth'>  Optional: false
      NODENAME:          couchdb0
    Mounts:
      /opt/couchdb/data from database-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kcn7m (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  database-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  openwhisk-couchdb-pvc
    ReadOnly:   false
  default-token-kcn7m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kcn7m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 openwhisk-role=core:NoSchedule
Events:
  Type     Reason     Age                    From                 Message
  ----     ------     ----                   ----                 -------
  Normal   Scheduled  <unknown>              default-scheduler    Successfully assigned openwhisk/openwhisk-couchdb-645bfbcb7d-8qd82 to hc7test2-0
  Normal   Pulled     32m (x5 over 33m)      kubelet, hc7test2-0  Container image "apache/couchdb:2.3" already present on machine
  Normal   Created    32m (x5 over 33m)      kubelet, hc7test2-0  Created container couchdb
  Normal   Started    32m (x5 over 33m)      kubelet, hc7test2-0  Started container couchdb
  Warning  BackOff    3m41s (x136 over 33m)  kubelet, hc7test2-0  Back-off restarting failed container
