### ISSUE TITLE
CouchDB Failed During Git Clone - Access Issue

### ISSUE THREAD

**Issue by jagan23527001** [apache/openwhisk-deploy-kube#596]
CouchDB pod getting failed while trying to clone the openwhisk github url. Our Kubernetes doesn't have access to internet,  is there any work around to run the cloud DB without cloning openwhisk github endpoint ?

Cloning into '/openwhisk'...
fatal: unable to access 'https://github.com/apache/openwhisk/': Failed to connect to github.com port 443: Connection timed out

**Comment by dgrove-oss** [comment]
There's nothing currently implemented in the Helm chart to directly help with deploying on clusters without internet connectivity. 

You could bypass this specific issue by configuring the Helm chart to use an external couchdb, but you'll just hit the same issue a few steps later when the job attempts to install the openwhisk-catalog (https://github.com/apache/openwhisk-catalog) from github.

There's an old feature request (#431) with a sketch of what would need to be done in general to support this scenario.

**Comment by jagan23527001** [comment]
Thanks Dgraove, will go over the other Request. is there a way to pass Proxy Environment variables to the pod through HELM scripts ?

**Comment by jagan23527001** [comment]
Close this, i added https_proxy to POD Env variable which access git clone.

**Comment by shakshisinghai** [comment]
> Close this, i added https_proxy to POD Env variable which access git clone.

Hello @jagan23527001 , @dgrove-oss ,
When I am deploying openwhisk, owdev-init-couchdb is giving below error,
Cloning into '/openwhisk'...
fatal: unable to access 'https://github.com/apache/openwhisk/': Could not resolve host: github.com
![image](https://user-images.githubusercontent.com/37688219/154168682-d594c808-2aed-4d38-ac11-0f1b1da2594a.png)

Could you please tell me how you added HTTP proxy to POD Env.

**Comment by GitHubDiom** [comment]
@shakshisinghai  facing the same issue, did you solve this proxy setting?

**Comment by shakshisinghai** [comment]
> @shakshisinghai facing the same issue, did you solve this proxy setting?

No, I am still facing the same issue. 
Though the Kubernetes have access to internet.

**Comment by GitHubDiom** [comment]
@DanielLee343 可以看一下log，如果是clone不下来的话这东西只有我们遇得到，检查一下网络问题，我们学校有短时间网络发神经会把github禁掉

**Comment by DanielLee343** [comment]
@GitHubDiom 感谢回复，我的log是这样
```
[lyuze@storage-2 openwhisk-deploy-kube]$ kubectl get pods -n openwhisk --watch
NAME                                  READY   STATUS     RESTARTS   AGE
owdev-alarmprovider-5548bf767-f5m8m   0/1     Pending    0          3m20s
owdev-apigateway-54bcf48f4d-7lgdv     1/1     Running    0          3m20s
owdev-controller-0                    0/1     Init:0/2   0          3m20s
owdev-couchdb-7598765b87-kvqx4        0/1     Pending    0          3m20s
owdev-gen-certs-45vbt                 0/1     Error      0          3m20s
owdev-gen-certs-kqtvf                 1/1     Running    0          16s
owdev-init-couchdb-4tf6k              0/1     Error      0          2m33s
owdev-init-couchdb-kw8bd              0/1     Error      0          3m20s
owdev-init-couchdb-mqtgq              0/1     Error      0          2m10s
owdev-init-couchdb-q2sdl              0/1     Error      0          2m56s
owdev-install-packages-prwwb          0/1     Init:0/1   0          3m20s
owdev-invoker-0                       0/1     Init:0/1   0          3m20s
owdev-kafka-0                         0/1     Pending    0          3m20s
owdev-kafkaprovider-7668d58-l9hsz     0/1     Init:0/1   0          3m20s
owdev-nginx-bcdcc6f65-rp8cl           0/1     Init:0/1   0          3m20s
owdev-redis-5c4d5b8d8-fwn6k           0/1     Pending    0          3m20s
owdev-wskadmin                        1/1     Running    0          3m20s
owdev-zookeeper-0                     0/1     Pending    0          3m20s
^C[lyuze@storage-2 openwhisk-deploy-kube]$ kubectl logs -n openwhisk owdev-init-couchdb-q2sdl
Cloning into '/openwhisk'...
fatal: unable to access 'https://github.com/apache/openwhisk/': Could not resolve host: github.com
```
很奇怪，但如果是学校网络问题为什么我`git clone https://github.com/apache/openwhisk/ `没任何问题
我还尝试了这个https://github.com/desktop/desktop/issues/4872#issuecomment-412950503 但也没用

**Comment by GitHubDiom** [comment]
@DanielLee343 我也是主机clone没问题，到了容器里面clone就出了问题，我是后面在实验室路由器上开了github相关域名走墙外解决的。在此之前我还试了一下专门给容器里面开个代理，clone的问题解决了，但是可能会引发[这个问题](https://github.com/apache/openwhisk-deploy-kube/issues/723#issue-1145838561)。

**Comment by lyudmilalala** [comment]
@shakshisinghai facing the same issue, not solved yet.
I am using a Ubuntu 22.04 VirtualBox VM as the k8s worker node. The host Windows system has a VPN proxy, which enables me to clone from github both on Windows and the Ubuntu VM. I am also confusing about how to add http proxy to the pod.
