### ISSUE TITLE
apiVersion error while installing openwhisk with helm

### ISSUE THREAD

**Issue by Nivekiba** [apache/openwhisk-deploy-kube#598]
When i try to install openwhisk using helm using this command
```
helm install ./helm/openwhisk/ --namespace=openwhisk --name=owdev -f mycluster.yaml
```

i'm getting this error

![image](https://user-images.githubusercontent.com/20845649/78659458-7aa7e200-78c3-11ea-8cb4-0f3a3f20d74a.png)

**Comment by dgrove-oss** [comment]
This means you are using a Helm v2 cli.  We now require Helm V3.
