### ISSUE TITLE
Deploy openwhisk on k8s cluster failed due to have no storageclass

### ISSUE THREAD

**Issue by ningyougang** [apache/openwhisk-deploy-kube#609]
Firstly, i deployed openwhisk on a single k8s cluster which is setup by `minikube`
After deployed, all openwhisk pods work well.

Later, i setup another k8s cluster with 4 nodes(1 master + 3 worker node) which is setup by `kubeadm`.
Then, i deployed openwhisk on this k8s cluster. steps as below
* add label
```
kubectl label nodes node-2 openwhisk-role=edge
kubectl label nodes node-3 openwhisk-role=core
kubectl label nodes node-4 openwhisk-role=invoker
```
* deploy using helm
```
cd /root/workspace/
git clone https://github.com/apache/incubator-openwhisk-deploy-kube.git
# create mycluster.yaml and modify ip
helm install ./helm/openwhisk --namespace=openwhisk --generate-name -f mycluster.yaml
```
After deployed, use `kubectl descript ${podName} -n openwhisk` to check,  exist error log
```
Normal FailedBinding 3m13s (x262 over 68m) persistentvolume-controller no persistent volumes available for this claim and no storage class is set
```
So i checked the storage class using `kubectl get storageclasses.storage.k8s.io`, it reported `no resource found`, but i checked in my single k8s cluster, exist a default storageclasse, e.g.
```
$ kubectl get storageclasses.storage.k8s.io
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  16d
```
In order to make my 4 nodes k8s cluster to install openwhisk successfully, one option is `apply above default storageclasse to my 4 nodes k8s cluster and redeploy again`

Have any other idea?

**Comment by dgrove-oss** [comment]
Your cluster either must have a default storage class defined or you must disable persistence in the Helm chart.  See https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/configurationChoices.md#persistence

**Comment by ningyougang** [comment]
Thanks! 

After added
```
k8s:
  persistence:
    enabled: false
```
to mycluster.yaml, it is ok now!
