### ISSUE TITLE
Cannot delete prewarm pod after execute helm delete

### ISSUE THREAD

**Issue by ningyougang** [apache/openwhisk-deploy-kube#610]
Recently, i am testing this repo to deploy openwhisk on k8s cluster.

When i deploy openwhisk on a multiple-nodes k8s cluster which is setup by `kubeadm`, it works well.

Finally, i execute `helm delete ${release} -n openwhisk` to delete the lease, but sometimes, the prewarm pods are not deleted, e.g.
```
# helm delete openwhisk-1592030974 -n openwhisk
release "openwhisk-1592030974" uninstalled
# kubectl get pods -n openwhisk
NAME                                                    READY   STATUS    RESTARTS   AGE
wskopenwhisk-1592030974-invoker-00-1-prewarm-nodejs10   1/1     Running   0          30m
wskopenwhisk-1592030974-invoker-00-4-prewarm-nodejs10   1/1     Running   0          24m
```
I executed `kubectl describe pod ${podName} -n openwhisk`, seems have no error logs.

If i want to delete, need to execute `kubectl delete pods ${podName} -n openwhisk` manually. 

Someone knows the reason why can't delete the prewarm pod via `helm delete ${releaseName} -n openwhisk`?

Node: but if i changed the configuration:`invoker.containerFactory.impl` from `kubernates` to `docker`, when execute `helm delete ${release} -n openwhisk`, can delete all resources thoroughly.

**Comment by dgrove-oss** [comment]
Hi.  Helm doesn't know about the pods the invokers create for user actions.  It only knows about the resource that are created by the `helm install`.  What I tend to do is just delete the openwhisk namespace after I use helm to delete the main install to get rid of the action pods.

**Comment by dgrove-oss** [comment]
Going to close this as a known limitation.  You can use the label on the pod to delete them all in one command if you don't want to delete the namespace.
