### ISSUE TITLE
Control when runtime container gets delete

### ISSUE THREAD

**Issue by nikolavukovic** [apache/openwhisk-deploy-kube#614]
Is it possible to control when an unused runtime container gets delete? I am performing some elasticity experiments on a system built on top of OpenWhisk, and I would like to control the inactivity time period after which a runtime container gets deleted. Is this even possible?

**Comment by style95** [comment]
Currently, there is no such feature to dynamically control the unused timeout.

Instead, there are some changes to dynamically control the number of prewarm containers based on heuristics.
https://github.com/apache/openwhisk/pull/4871

**Comment by nikolavukovic** [comment]
Ok, thank you.
