### ISSUE TITLE
Deployment of openwhisk in kubernetes using custom docker for controller and/or invoker 

### ISSUE THREAD

**Issue by Nivekiba** [apache/openwhisk-deploy-kube#631]
Hello,

As we can see in this image (a part of the helm/openwhisk/values.yaml) :
![image](https://user-images.githubusercontent.com/20845649/90622436-fc623180-e20c-11ea-8d7e-22204ac2f47e.png)
i want to know if it's possible to change the controller docker image and use a custom one ? If yes, how ?

Because when i try it by my own, the **install-packages** pod stuck at *Init: 0/1* state

PS: i am regenerating the controller docker image by using `./gradlew distDocker` and then i want to reference the newly created images in the deployment of my openwhisk cluster

**Comment by dgrove-oss** [comment]
That is the correct way to use a different image (https://github.com/apache/openwhisk-deploy-kube/#deploying-a-locally-built-docker-image).   The image does have to be published to a docker registry that your cluster can pull from.   It also has to contain a correct controller ;).   Try getting the details/logs from the controller pod to see what is happening.  Is the cluster unable to pull your image?  Is the image pulled but crashing for some reason?   Did you perhaps forget to label a node with invoker affinity (https://github.com/apache/openwhisk-deploy-kube/#initial-setup), which would result in no invokers being deployed, which is one reason why the install-packages pod could be stuck in `Init: 0/1` state.

**Comment by Nivekiba** [comment]
Hi, 
i think it is a correct controller because i just rebuild the controller image using the `./gradlew distDocker` command. 

From the controller pod logs, everything is working well in controller

From the install-pakcages logs, i have this warning ```MountVolume.SetUp failed for volume "task-dir" : failed to sync configmap cache: timed out waiting for the condition```.

 And don't even see this error on google after my search.

And i also want to notice that when i use the default controller config but i use a customized container image for the invoker pod, everything also works well

**Comment by dgrove-oss** [comment]
Closing as stale.
