### ISSUE TITLE
Documentation: newest version of kind not supporting kubeconfig-path

### ISSUE THREAD

**Issue by Mec-iS** [apache/openwhisk-deploy-kube#641]
Hi,
I am going through the documentation and when I reached
> Next, configure kubectl by executing
>    `KUBECONFIG="$(kind get kubeconfig-path)"`

it happened to notice that the version of `kind` I am using (`kind version 0.9.0`) does not have at all the command `get kubeconfig-path`. The only affine command I found in the help for version 0.9 is `kind get kubeconfig` but this returns an object and not a path.
How can I find out the path to assign to `KUBECONFIG` with `kind version 0.9.0`?

**Comment by dgrove-oss** [comment]
I'm pretty sure this step is no longer needed; its a leftover from kind 0.6 or so.   I'm using kind 0.8 and I don't need to do it.

**Comment by Mec-iS** [comment]
can confirm that I went through without it.
