### ISSUE TITLE
Pods Never Starting Up

### ISSUE THREAD

**Issue by dergoose** [apache/openwhisk-deploy-kube#647]
![chrome_gLGciEjdh1](https://user-images.githubusercontent.com/20442160/96032059-28281f00-0e2c-11eb-9f8a-ee5425167d35.png)

I'm on Ubuntu 18.04 and my pods are never getting passed this state even days after.

My yaml file is all correct and I've went through all the logs of the pods and there's nothing out of the ordinary. 

Help!

**Comment by dgrove-oss** [comment]
My first guess would be that your cluster doesn't have a DefaultStorageClass properly configured.  The various pods that are in pending state want to allocate persistent volumes.  You can try disabling persistence and redeploying the chart as one sanity check.  See https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/configurationChoices.md#persistence

**Comment by dergoose** [comment]
This was indeed the issue.

Thanks!
