### ISSUE TITLE
Can not call web action from browser

### ISSUE THREAD

**Issue by soko99** [apache/openwhisk-deploy-kube#655]
How can I call a web action from my browser, when my OpenWhisk deployment is on a company sandbox server?

I have an OpenWhisk deployment setup on a company sandbox server using this guide: [Deploying OpenWhisk on kind][1]. The server is running CentOS 7. I created a web action and I am able to call with `curl -k https://apiHostName:apiHostPort/api/v1/web/guest/demo/hello?name=myName` where apiHostName and apiHostPort are the values defined in mycluster.yaml. However, trying to access the above url from my browser returns ERR_CONNECTION_TIMED_OUT. 

    [root[DEV]@vx3a27 wskcluster]# kubectl -n openwhisk get svc
    NAME               TYPE        CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
    owdev-apigateway   ClusterIP   10.96.9.60      A.B.C.D        8080/TCP,9000/TCP            6d1h
    owdev-controller   ClusterIP   10.96.104.180   <none>         8080/TCP                     6d1h
    owdev-couchdb      ClusterIP   10.96.40.104    <none>         5984/TCP                     6d1h
    owdev-kafka        ClusterIP   None            <none>         9092/TCP                     6d1h
    owdev-nginx        NodePort    10.96.84.3      A.B.C.D        80:31486/TCP,443:31001/TCP   6d1h
    owdev-redis        ClusterIP   10.96.84.177    <none>         6379/TCP                     6d1h
    owdev-zookeeper    ClusterIP   None            <none>         2181/TCP,2888/TCP,3888/TCP   6d1h

I have tried setting the external API of both my nginx and apigateway services as seen above, where A.B.C.D is the IP of my sandbox obtained with `ifconfig`. Running both `curl -k` and the browser with A.B.C.D yields ERR_CONNECTION_REFUSED.

What else can I try to get this to work?

  [1]: https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-kind.md

**Comment by style95** [comment]
Are you able to curl against the nginx IP?

You should get something like this:
```
$ curl 10.107.131.27
{"api_paths":["/api/v1"],"description":"OpenWhisk","limits":{"actions_per_minute":60,"concurrent_actions":100,"max_action_duration":360000,"max_action_logs":1048576,"max_action_memory":1073741824,"min_action_duration":100,"min_action_logs":0,"min_action_memory":536870912,"sequence_length":50,"triggers_per_minute":240},"runtimes":{...},"support":{"github":"https://github.com/apache/openwhisk/issues","slack":"http://slack.openwhisk.org"}}
```

Since the error is `CONNECTION_REFUSED` rather than `CONNECTION_TIMEDOUT`, I suppose your ow deployment is not complete.
There might be some failures in some pods.
It seems nginx cannot connect to controllers.

**Comment by soko99** [comment]
No, I get this: 
```
# curl 10.96.84.3
curl: (7) Failed connect to 10.96.84.3:80; Connection refused
```

Also, looking into the pods I found an error in the owdev-tests-smoketest pod:
```
# kubectl -n openwhisk get pods
NAME                                     READY   STATUS      RESTARTS   AGE
owdev-alarmprovider-6d54d457f8-2sc6p     1/1     Running     0          19m
owdev-apigateway-6b6d6cc4ff-rw57j        1/1     Running     0          19m
owdev-controller-0                       1/1     Running     0          19m
owdev-couchdb-54b489b58d-vpmsh           1/1     Running     0          19m
owdev-gen-certs-w6ph2                    0/1     Completed   0          19m
owdev-init-couchdb-9zbn9                 0/1     Completed   0          19m
owdev-install-packages-g6mnz             0/1     Completed   0          19m
owdev-invoker-0                          1/1     Running     0          19m
owdev-kafka-0                            1/1     Running     0          19m
owdev-kafkaprovider-84bfb77776-9p2r4     1/1     Running     0          19m
owdev-nginx-6966cdf9dc-hkq2d             1/1     Running     0          19m
owdev-redis-5bc6bf6b4c-6b5z2             1/1     Running     0          19m
owdev-tests-package-checker              0/1     Completed   0          2m48s
owdev-tests-smoketest                    0/1     Error       0          2m45s
owdev-wskadmin                           1/1     Running     0          19m
owdev-zookeeper-0                        1/1     Running     0          19m
wskowdev-invoker-00-1-prewarm-nodejs10   1/1     Running     0          17m
wskowdev-invoker-00-2-prewarm-nodejs10   1/1     Running     0          17m
wskowdev-invoker-00-4-prewarm-nodejs10   1/1     Running     0          12m
wskowdev-invoker-00-5-prewarm-nodejs10   1/1     Running     0          4m10s
```

**Comment by style95** [comment]
I recommend looking into controller or nginx logs as you even cannot connect to it.

**Comment by dgrove-oss** [comment]
Closing as stale
