### ISSUE TITLE
Create a Helm repo for openwhisk deployments

### ISSUE THREAD

**Issue by onmyflow** [apache/openwhisk-deploy-kube#662]
First of all: Im not sure if this request belongs to this repo or the "openwhisk-core" repo.

Since Openwhisk has now reached version 1.0.0, it should be of a priority to supply a helm repository (can be served from github itself) for Helm Charts. It is a common workflow for Helm deployments, that anyways rely on Helm for their installation, to provide a single URI for the Chart, from which helm can pull a specified version. Cloning the project (the docs also mention one should just clone the repository -- ergo the master branch without any version constraints) everytime one wants to upgrade/install the Chart seems quite cumbersome and unsafe (because of missing versioning). It makes it hard to create "Infrastructure as Code" if you need to manually track a git repository in your "Infrastructure as code project".

**Comment by dgrove-oss** [comment]
This is the right place for the issue; it is a reasonable suggestion.  Would be happy to get a PR if you have time.

**Comment by dgrove-oss** [comment]
Seeing if I can manage to get our website setup to allow me to host one at openwhisk.apache.org/charts or similar.

**Comment by dgrove-oss** [comment]
You can now do `helm repo add openwhisk https://openwhisk.apache.org/charts` and install the 1.0.0 helm chart from helm repository.  Leaving the issue open until I update the documentation...
