### ISSUE TITLE
action instance number limited

### ISSUE THREAD

**Issue by whoszus** [apache/openwhisk-deploy-kube#663]
action can only support 8 instances at the same time when the function is executed, where is this limitation configured?
How can I modify it to support more "simultaneous instances"?

**Comment by ningyougang** [comment]
Sorry, what's mean `8 instances`?

**Comment by dgrove-oss** [comment]
You need to configure the system to tell it how much memory is available for user actions.  The default is 2Gb available (https://github.com/apache/openwhisk-deploy-kube/blob/master/helm/openwhisk/values.yaml#L125). With the default of 256MB actions,    2048 / 256 = 8.

**Comment by whoszus** [comment]
Thank you, it works. @dgrove-oss
