### ISSUE TITLE
Tutorial based on Docker for mac contain a outdated command (?)

### ISSUE THREAD

**Issue by Sladerix** [apache/openwhisk-deploy-kube#702]
Hi everyone, i'm trying to following the guide to install openwhisk on the kubernetes cluster provided by docker.
it says to execute this command: `kubectl config use-context docker-for-desktop`
but it does not work. searching on google i found the official website page https://docs.docker.com/desktop/kubernetes/ where this command is used `kubectl config use-context docker-desktop` i think is the same thing, with the difference that this works

**Comment by dgrove-oss** [comment]
Hi,  I think you are right...docker changed this a while ago.  If you wanted to submit a PR to fix the docs that would be great

**Comment by Sladerix** [comment]
> Hi, I think you are right...docker changed this a while ago. If you wanted to submit a PR to fix the docs that would be great

I think i've done

**Comment by dgrove-oss** [comment]
Fixed in #783
