### ISSUE TITLE
Get whisk.ingress.apiHostName automatically ?

### ISSUE THREAD

**Issue by pankaj-dahiya** [apache/openwhisk-deploy-kube#705]
Dear team,

I knew there is a small advantage we get by asking the user to provide whisk.ingress.apiHostName at day zero... But this is actually not feasible. Because once user deploys the helm chart by providing whisk.ingress.apiHostName and in future, if machine restarts its IP may be changed. And if that happens then our cluster which will automatically start running after machine restart will fail due to IP mismatch.

So want to know what open whisk team or other guys are handling this situation.

**Comment by pankaj-dahiya** [comment]
@dgrove-oss Do you have any recommended solution for this!

**Comment by rabbah** [comment]
Where are you deploying openwhisk @pankaj-dahiya? Typically, as Dave noted, there is a stable domain name and if the IP address changes, one updates the DNS record for the deployment. If you don't have a static IP, how do you communicate the change of IP to the users of your openwhisk cluster?

**Comment by pankaj-dahiya** [comment]
Hi @rabbah, I am deploying this in an isolated environment, where users will access the app via private IP (that will be static).  But there could be a reason, that in future the IT team may consider a change in IP address (another static IP). In that case, all other services will still work fine, but not open whisk, and thus they must have to manually handle this thing! That's why I opened this ticket, which is a kind of feature request.
