### ISSUE TITLE
How to perform HTTP requests from an action

### ISSUE THREAD

**Issue by Sladerix** [apache/openwhisk-deploy-kube#715]
Hi everyone, i've a doubt.. 
i've a python http server running on my host pc, then i've a OpenWhisk deployment running on kubernetes that comes with docker.

I've an action that needs to make HTTP requests to the server running on my machine... but it fails because cannot reach the server, probably due to the separation made by docker (?)...

there is a simple way to solve the thing?

Thanks in advance

**Comment by dimgiagos44** [comment]
Maybe one approach is to deploy the HTTP server as a pod(Cluster-IP) in Kubernetes and then make your calls to that specific endpoint...Not sure though if that is the best you can do

**Comment by Sladerix** [comment]
> Maybe one approach is to deploy the HTTP server as a pod(Cluster-IP) in Kubernetes and then make your calls to that specific endpoint...Not sure though if that is the best you can do

thansk for the tip :D
