### ISSUE TITLE
Openwhisk only allows 8 invocations at a time i

### ISSUE THREAD

**Issue by ankushshr1993** [apache/openwhisk-deploy-kube#728]
Openwhisk allows only 8 pods to be created for n number of invocations at a time. For performance testing, we need to increase the number of pods at a time.Is this a limitation of open whisk or can configure it to eradicate this limitation

**Comment by dgrove-oss** [comment]
See https://github.com/apache/openwhisk-deploy-kube#scale-up-your-openwhisk-deployment

**Comment by dgrove-oss** [comment]
> containerPool.userMemory: total memory available per invoker instance. Invoker uses this memory to create containers for user-actions. The concurrency-limit (actions running in parallel) will depend upon the total memory configured for containerPool and memory allocated per action (default: 256mb per container).

**Comment by ankushshr1993** [comment]
Thanks, I'll check it out.

**Comment by ankushshr1993** [comment]
Hi David,

As per your suggestion and described in the link I updated the
mycluster.yaml file by adding actionsInvokesConcurrent: 50 but it still
creates only 8 pods .I am trying to figure out what would be the value of
contaierPool.userMemory: forexample for 50 concurrent pods.

I have attached mycluster.yaml file used in my deployment for your
reference.I would request for your advice on this.

Regards
Ankush Sharma

**Comment by dgrove-oss** [comment]
You need to increase `containerPool.userMemory`.  The default values is 2048m, which corresponds to 8 pods of 256m each (the default memory size for a user container).    If you want 50 concurrent actions, you have one invoker, and your actions use the default of 256m, then you need containerPool.userMemory = 50*256.

**Comment by ankushshr1993** [comment]
Hi David,

I have tried these values but it stil not working.Can you please have a
look at mycluster.yaml file and help if I am keeping it correctly


Regards
Ankush Sharma

**Comment by ankushshr1993** [comment]
Thanks a lot david for your help

I was putting the variables and values in the wrong section.I figured it
out.

Thanks again
Regards
Ankush Sharma
