### ISSUE TITLE
Synactic error: openwhisk-deploy-kube/helm/openwhisk/runtimes.json is invalid JSON

### ISSUE THREAD

**Issue by konstantin-palikarsky** [apache/openwhisk-deploy-kube#743]
Hi,
I wasn't sure if opening an issue for such a bug requires more extensive logs, If it does I will add them.

What the issue is:
The file runtimes.json in the helm/openwhisk folder is not valid JSON.

How to reproduce:
Just plug it into any JSON validator e.g:https://jsonlint.com/ . Alternatively attempt to deploy openwhisk using ./helm/openwhisk and check the owdev-controller-0 pod's logs after it errors out. 

Suggested fix:
Deleting the comma on line 44 allowed me to deploy openwhisk correctly.

**Comment by dgrove-oss** [comment]
Thanks for the report.  Must have messed up a merge in the last change to that file.
