### ISSUE TITLE
Error with Installation 

### ISSUE THREAD

**Issue by g83wang** [apache/openwhisk-deploy-kube#748]
Hi, 

Thank you for looking into this issue.

I use the helm chart to deploy openwhisk on a local kind cluster (as instructed here: https://github.com/apache/openwhisk-deploy-kube/blob/master/README.md#initial-setup). All pods are up but get an error with the owdev-install-packages-27snr. 
![image](https://user-images.githubusercontent.com/43029806/186017213-aa75ef2c-a33c-41c8-8530-8e1f653d3b1e.png)
I have already labelled some kind workers as invokers. 
Here is the log for owdev-install-packages-27snr:
![image](https://user-images.githubusercontent.com/43029806/186017618-57d9eaa6-abe9-42e1-9baf-10ade2f952b3.png)
Here is my configuration file (mycluster.yaml):
![image](https://user-images.githubusercontent.com/43029806/186018136-e06cdf5b-fb06-4fe3-a036-9a259f330371.png)
Here is the kind-cluster.yaml:
![image](https://user-images.githubusercontent.com/43029806/186018352-3d7d041a-a92c-4baa-bc7a-d4fb13cf78c8.png)

Could I get some idea on this issue and how to fix it?
Thank you.

**Comment by obrr-hhx** [comment]
I also have met this problem, I guess this is about the GFW, so i fix it  through changing the file myTask.sh in the directory `helm/openwhisk/configMapFiles/installPackages/myTask.sh` by setting the npm proxy.

I add the two following command in this file
`npm config set proxy http://<your proxy ip>:<proxy port>`
`npm config set registry "http://registry.npmjs.org/"`

and I use the following command to deploy the openwhisk
`helm install owdev ./helm/openwhisk -n openwhisk --create-namespace -f ./deploy/kind/mycluster.yaml`

If you want to do some operations in the install-packages pod, I suggest you use command like
`kubectl exec --stdin --namespace=openwhisk --tty owdev-install-packages-27snr -- /bin/bash`
